2.1. Data Manipulation

2.2. Data Preprocessing

2.3. Linear Algebra

2.5. Automatic Differentiation

3.1. Linear Regression

3.2. Object-Oriented Design for Implementation

3.4. Linear Regression Implementation from Scratch



4.1. Softmax Regression

4.2. The Image Classification Dataset

4.3. The Base Classification Model

4.4. Softmax Regression Implementation from Scratch

4.3 Automatic Differentiation (It was a typo)

5.1. Multilayer Perceptrons

5.2. Implementation of Multilayer Perceptrons

5.3. Forward Propagation, Backward Propagation, and Computational Graphs

## 2

### 2.1. Data Manipulation

In [28]:
import torch

In [29]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [30]:
x.numel()

12

In [31]:
x.shape

torch.Size([12])

In [32]:
x = x.reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [35]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [36]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [38]:
x[1, 2] = 17
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
x[:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [40]:
torch.exp(x)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [45]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2,2,2,2])

print(x // y, x % y)    ## these also works!
x+y, x-y, x*y, x/y, x**y

tensor([0., 1., 2., 4.]) tensor([1., 0., 0., 0.])


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))